meta_product_name: "iChooze"
meta_title: "iChooze - Spend less time choosing, more time watching !"
meta_description: "iChooze is the ultimate movie suggestion generator."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
